#推荐方案
spring:
  application:
    name: com.putai.msrecommend
  jpa:
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8182
  servlet:
    context-path: /msrecommend

eureka:
  client:
    enabled: false
    fetch-registry: false