#推荐方案
spring:
  application:
    name: com.putai.msrecommend
  jpa:
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8182
  servlet:
    context-path: /msrecommend

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.104:8080/eureka/  #指定Eureka注册中心url
  instance:
    prefer-ip-address: true
