#健康档案
spring:
  application:
    name: com.putai.msarchive
  jpa:
    database: MYSQL
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8181
  servlet:
    context-path: /msarchive

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/  #指定Eureka注册中心url
  instance:
    prefer-ip-address: true
