#健康档案
spring:
  application:
    name: com.pt.msarchive
  jpa:
    database: MYSQL
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8181
  servlet:
    context-path: /msarchive

eureka:
  client:
    enabled: false
    fetch-registry: false
